spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL :jdbc:postgresql://localhost:10111/rgmbdatabase}
    username: ${JDBC_DATABASE_USERNAME :postgres}
    password: ${JDBC_DATABASE_PASSWORD :11number}

  aop:
    auto: false

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  thymeleaf:
    enabled: true
    encoding: UTF-8
    cashe: false
    check-template: true
    check-template-location: true
#   prefix: classpath:/templates/
#   suffix html
    mode: HTML
    template-resolver-order: 0

