spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  aop:
    auto: false



  thymeleaf:
    enabled: true
    encoding: UTF-8
    cashe: false
    check-template: true
    check-template-location: true
#   prefix: classpath:/templates/
#   suffix html
    mode: HTML
    template-resolver-order: 0

