spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:10111/rgmbdatabase
    username: postgres
    password: 11number

  aop:
    auto: false

  thymeleaf:
    enabled: true
    encoding: UTF-8
    cashe: false
    check-template: true
    check-template-location: true
#   prefix: classpath:/templates/
#   suffix html
    mode: HTML
    template-resolver-order: 0
